import { chromium } from 'playwright';
const b = await chromium.launch({ headless: true, args: ['--use-angle=metal','--enable-gpu','--ignore-gpu-blocklist','--hide-scrollbars','--mute-audio'] });
const page = await b.newPage({ viewport: { width: 1600, height: 900 } });
await page.addInitScript(() => { const R = window.WebSocket; class D extends EventTarget { constructor(){super();this.readyState=3;} send(){} close(){} } window.WebSocket = function(u,p){ return p==='vite-hmr'? new D(): new R(u,p); }; });
await page.goto('http://127.0.0.1:5178/', { waitUntil: 'domcontentloaded' });
await page.waitForFunction(() => !!window.__leeward, null, { timeout: 60000 });
await page.evaluate(() => { const w = window.__leeward.world;
  Object.assign(w.settings, { quality: 'ultra', adaptiveResolution: false, renderScale: 1 });
  Object.assign(w.env, { timeOfDay: 12.7, windSpeed: 10.5, turbidity: 2, visibility: 34000, seaState: 4, waveHeight: 2 });
  w.bus.emit('settings:changed'); w.bus.emit('capture:scene', {}); });
await page.waitForTimeout(8000);
const res = await page.evaluate(() => {
  const w = window.__leeward.world, r = w.renderer, gl = r.getContext();
  const p = globalThis.__rcPipe, e = p.exposure, t = p.targets;
  const scene = t.get('scene', w.size.width, w.size.height, 'rgba16f', { depth: true });
  const lum = t.get('expLum', 64, 64, 'r16f', { nearest: true });
  const partial = t.get('expPartial', 64, 32, 'r16f', { nearest: true });
  const result = t.get('expResult', 1, 1, 'rgba32f', { nearest: true });
  const N = 40;
  const time = (label, fn) => {
    fn(); gl.finish();
    const t0 = performance.now();
    for (let i = 0; i < N; i++) fn();
    gl.finish();
    return [label, +((performance.now() - t0) / N).toFixed(3)];
  };
  const out = [];
  const lu = e.lumPass.uniforms;
  lu.tScene.value = scene.texture;
  lu.uSceneTexel.value.set(1 / scene.width, 1 / scene.height);
  lu.uFootprint.value.set(scene.width / 64, scene.height / 64);
  out.push(time('lum', () => e.lumPass.render(r, lum)));
  e.histPass.uniforms.tLum.value = lum.texture;
  out.push(time('histogram', () => e.histPass.render(r, partial)));
  e.resolvePass.uniforms.tPartial.value = partial.texture;
  out.push(time('resolve', () => e.resolvePass.render(r, result)));
  out.push(time('readSyncx1', () => { try { r.readRenderTargetPixels(result, 0, 0, 1, 1, e.readBuffer); } catch (x) {} }));
  const buf = new Float32Array(4);
  out.push(time('readAsyncCall', () => { r.readRenderTargetPixelsAsync(result, 0, 0, 1, 1, buf).catch(() => {}); }));
  r.setRenderTarget(null);
  return out;
});
console.log(res.map(([k, v]) => `${k.padEnd(14)} ${v} ms`).join('\n'));
await b.close();
