import { chromium } from 'playwright';
const b = await chromium.launch({ headless: true, args: ['--autoplay-policy=no-user-gesture-required','--enable-unsafe-swiftshader','--use-angle=metal','--enable-gpu','--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
p.on('console', m => console.log(m.type().toUpperCase(), m.text().slice(0,300)));
p.on('pageerror', e => console.log('PAGEERROR', e.message.slice(0,500)));
p.on('requestfailed', r => { if (!/fonts\./.test(r.url())) console.log('REQFAIL', r.url().slice(0,140), r.failure()?.errorText); });
await p.route('**://fonts.googleapis.com/**', r => r.abort());
await p.route('**://fonts.gstatic.com/**', r => r.abort());
await p.goto('http://127.0.0.1:5178/', { waitUntil: 'commit', timeout: 30000 });
await p.waitForTimeout(20000);
console.log('leeward?', await p.evaluate(() => ({ has: !!window.__leeward, keys: window.__leeward ? Object.keys(window.__leeward) : null, ext: window.__leeward?.world?.ext ? Object.keys(window.__leeward.world.ext) : null })));
await b.close();
